### ISSUE TITLE
Suggested content

### ISSUE THREAD

**Issue by muehlhaus** [fslaborg/fslaborg.github.io#5]
This content needs to be produced or linked:
* [ ] getting started
* [ ] install F# + environment -> notebooks
* [ ] advantages of F# for data science
* [ ] data science packages
* [ ] reading and material
* [ ] Interop with...

**Comment by WalternativE** [comment]
Maybe a "big picture" getting started section? I was thinking about the "house price" dataset from kaggle. Loading it into a deedle frame, doing some easy operations (filtering rows, slicing columns) to tidy the dataset, adding a couple of nice visualizations using Plotly.NET, maybe creating one or two hypothesis tests and then doing an ANOVA or a linear model. Just to show how parts of the stack work together. I could imagine you could build additional guides integrating FLIPS, Keras.NET or ML.NET.

**Comment by ZimmerD** [comment]
So I started off with a first try on the suggested section! 

As suggested I went for the housing data set, did an analysis using different parts of the stack and tried to build a little story around it. It could also serve as a starting point of a little series of some more detailed articles.

You can find the current state in this [gist](https://gist.github.com/ZimmerD/05c68a18f526b73c2aaaa991e2ef0deb), but I will soon move it to the new documentation template and issue a pull request so that we can discuss it here, what do you think?

**Comment by bvenn** [comment]
"Getting started" and various other blog posts and tutorials were written in the meantime, so this issue seems closed for me.
