### ISSUE TITLE
Allow user to specify number of rows in output grids

### ISSUE THREAD

**Issue by mjhomb** [fslaborg/fslaborg.github.io#5]
When including Deedle series and frames in the output we cannot control the number of rows being included - ideally we would like to set the startRowCount and endRowCount paramteres being passed to the markdown formatter in Formatter.fs  - perhaps via some configuration we could pass to Journal.Process?

**Comment by tpetricek** [comment]
This is a great idea - it should certainly be configurable. 

Do you think you'd want to change this for individual frames, or do you think it should be a whole-journal property? 

Doing it whole-journal would be quite easy:

 - Add the parameter [to the context](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.Runner/Runner.fs#L22)
 - Change the place where [Deedle frames are formatted](https://github.com/fslaborg/FsLab/blob/master/src/FsLab.Runner/Formatters.fs#L282)

I'll eventually get to do this, but if you want to look into that and send a PR, that would be amazing :-). It should be doable using the above pointers! I think the easiest way to test it is to download the [journal template](http://github.com/fslaborg/FsLab.Templates), build & run it; then build FsLab.Runners and copy the produced binaries into the template (then you can re-run the journal and see if it worked).

As for the per-output option, that is a bit trickier, because we'd need some way to specify this, so that would need more thinking.

**Comment by mjhomb** [comment]
Thanks for the reply. A whole journal property would meet our needs - I'll have a go at following your pointers next week and try to get back to you with something.

**Comment by tpetricek** [comment]
Fantastic - I'll be watching this thread, so if you need any more pointers, definitely let me know!

**Comment by mjhomb** [comment]
I have followed your tips and done something, usage looks like this in __build.fsx__:

```fsharp
let ctx = ProcessingContext.Create(__SOURCE_DIRECTORY__).With(fun p ->
  { p with
      OutputKind = OutputKind.Html;
      FormatConfig = FormatConfig.Create().With( fun c ->
        { c with
            StartRowCount = 33; });
      Output = ...
```
Would you like me to check that in or should I just end you the diff file? Thanks

**Comment by tpetricek** [comment]
Finally merged this, sorry about the delay!
